### ISSUE TITLE
Access was denied when calling Glue in deployment

### ISSUE THREAD

**Issue by tkoba-aws** [aws-samples/amazon-chime-voiceconnector-cdr-processing#28]
### Describe the bug

When deploying I get the following permission error and the deployment rolls-back.

`17:49:23 | CREATE_FAILED        | AWS::KinesisFirehose::DeliveryStream | KinesisResourcescd...veryStreamA711DC23
Resource handler returned message: "Access was denied when calling Glue. Please ensure that the role specified in the data format conversion configuration has the necessary p
ermissions. User: arn:aws:sts::XXXXXXXX:assumed-role/amazon-chime-sdk-voice-co-KinesisResourcesFirehose-XXXXXXXX/XXXXXXXX is not authorized to
perform: glue:GetTableVersions on resource: arn:aws:glue:us-east-1:XXXXXXXX:catalog because no identity-based policy allows the glue:GetTableVersions action (Service: AWS
Glue; Status Code: 400; Error Code: AccessDeniedException; Request ID: XXXXXXXX; Proxy: null) (Service: Firehose, Status Code: 400, Request ID: d3
6572fc-f0f8-3c2c-8f83-7d2d691c0cef, Extended Request ID: XXXXXXXX)" (RequestToken: XXXXXXXX, HandlerErrorCode: InvalidRequest)`

### Expected behavior

Expecting to deployment to complete successfully.

### Current behavior

Deployment fails and rolls-back.

### Steps to Reproduce

yarn launch

### AWS SDK version used

aws-cli/2.11.16

### Operating System and version

local Mac and Cloud9 environment

**Comment by schuettc** [comment]
Fixed with this commit: https://github.com/aws-samples/amazon-chime-voiceconnector-cdr-processing/commit/1b3f7c7ebdc2efbf78c3ee7b3c866f0cec3ba7f3
